spring:
  mustache:
    suffix: .html
    cache: false
  mvc:
    favicon:
      enabled: false

  output:
    ansi:
      enabled: ALWAYS

server:
  port: 8082

logging:
  level:
    root: INFO

gpayments:
  asAuthUrl: https://api.as.testlab.3dsecure.cloud:7443
  baseUrl: http://localhost:8082
  certFileName: # Client Certificate file (.p12 or .pfx) path

